name: anospp_analysis
channels:
  - conda-forge
  - bioconda
  - nodefaults
dependencies:
  # non-python requirements
  - mamba
  - blast=2.12.0
  - fasttree=2.1.10
  - mafft=7.490
  # python requirements should go to pyproject.toml
  # this section only deals with basic poetry installation
  - python=3.10.*
  - pip
  - pip:
    - "poetry>=1.2"