name: anospp_analysis
channels:
  - conda-forge
  - bioconda
  - nodefaults
dependencies:
  # non-python requirements
  - blast
  - fasttree
  - mafft
  # python requirements should go to pyproject.toml
  # this section only deals with basic poetry installation
  - python=3.10.*
  - pip
  - pip:
    - "poetry>=1.2"