{% set name = "anospp-analysis" %}
{% set version = "0.3.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/anospp_analysis-{{ version }}.tar.gz
  sha256: 6a4378afe0315966037fd7f77ec2c4e25761037b34bec07415c0b9c418f9666c

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  run_exports:
    - {{ pin_subpackage(name, max_pin="x.x") }}

requirements:
  host:
    - pip
    - poetry 1.5
    - python 3.10.*
  run:
    - python 3.10
    - cutadapt 4.9
    - numpy 1.26.3
    - scipy 1.14.1
    - pandas 2.2.2
    - seaborn 0.13.2
    - bokeh 3.5.2
    - keras 2.15.0
    - tensorflow-base 2.15.0
    - blast 2.14
    - fasttree
    - mafft

test:
  imports:
    - anospp_analysis
  commands:
    - anospp-prep -h
    - anospp-qc -h
    - anospp-plasm -h
    - anospp-nn -h
    - anospp-vae -h
    - anospp-agg -h

about:
  home: https://pypi.org/project/anospp-analysis/
  summary: ANOSPP data analysis
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - amakunin
