{% set name = "anospp-analysis" %}
{% set version = "0.1.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/anospp_analysis-{{ version }}.tar.gz
  sha256: 402930a959233daa4e0a4255d134eceb07d65421234be422c36e9874c51ecef0

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - poetry
    - python
  run:
    - biopython
    - cutadapt
    - numpy 
    - pandas
    - python
    - seaborn
    - blast
    - fasttree
    - mafft

test:
  imports:
    - anospp_analysis
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/anospp-analysis/
  summary: ANOSPP data analysis
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - amakunin
